apiVersion: v1
kind: ConfigMap
metadata:
  name: projects-postgres-config
data:
  POSTGRES_DB: projectsDB
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: projects-postgres-service
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: projects-postgres
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: projects-postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projects-postgres
  template:
    metadata:
      labels:
        app: projects-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: projects-postgres-config
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: projects-postgres-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: projects-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
