# Generated by Django 4.2.14 on 2024-08-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='materials',
            field=models.ManyToManyField(related_name='services', to='estimator.material'),
        ),
    ]
