# Generated by Django 4.2.14 on 2024-08-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0003_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='session_key',
            field=models.CharField(default='', max_length=40),
        ),
    ]
