# Generated by Django 4.2.14 on 2024-08-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0004_estimate_comment_estimate_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='saved_to_smeta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='session_key',
            field=models.CharField(max_length=40),
        ),
    ]
